### ISSUE TITLE
Use separate package for extinction curve

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#132]
As brought up by @karllark over at spacetelescope/pysynphot#54
<hr/>
There are external packages that provide extinction curves for python. One of these packages could be used instead of the numerical tables currently used.
Pros: offload the updating of the extinction curves to the "community"
Cons: Less control of the provided curves (but could be mitigated by automated testing against existing numerical results?)

Possible packages I know of:
https://github.com/kbarbary/extinction
https://github.com/karllark/dust_extinction
https://github.com/karllark/dust_attenuation
https://github.com/eblur/dust

In the interest of full disclose: I'm responsible for the 2nd package that has the aspiration of being an astropy affiliated package. The goals of my package are to provide dust extinction curves to the community and for use in dust extinction research (mine and others). Feedback is always welcomed.

...

I agree that only the dust_extinction package uses the astropy.modeling framework. I'm finding using this framework very powerful and useful. I've also been using the astropy.units framework. Very nice as well.

**Comment by eteq** [comment]
I think this is highly desirable - that way it's not the responsibility of `synphot` to keep up with the latest scientific needs and desires regarding extinction laws.  In fact, medium- to long-term it might be desirable to deprecate the extinction stuff in `synphot` *entirely* and instead have the documentation redirect people to these other packages so as to consolidate the community's efforts.

But the short-term step in that direction would definitely be to do as suggested here.

**Comment by pllim** [comment]
I guess we can start with @karllark 's packages, especially since such integration is already laid out in [color excess tutorial](https://github.com/astropy/astropy-tutorials/blob/master/tutorials/notebooks/color-excess/color-excess.ipynb). I think this is the key here below (excerpt from the tutorial):

```python
# Initialize the extinction model and choose the extinction, here Av = 2.
ext = CCM89(Rv=3.1)
Av = 2.

# Create a wavelength array.
wav = np.arange(0.1, 3, 0.001)*u.micron

# Make the extinction model in synphot using a lookup table.
ex = ExtinctionCurve(ExtinctionModel1D,
                     points=wav, lookup_table=ext.extinguish(wav, Av=Av))
sp_ext = sp_norm*ex
sp_ext.plot(left=1, right=15000, flux_unit='flam',
            title='Normed Blackbody with Extinction')
```

I'll have to investigate how this can be baked into `synphot` API. Maybe @karllark has ideas?

**Comment by karllark** [comment]
@pllim : Not sure what you are asking here.
Is there a reason that the dust_extinction model is being wrapped in `ExtinctionCurve`?  It could be used directly as `sp_ext = sp_norm*ext.extinguish(wave, Av=Av)`.  Likely there is something special about `ExtinctionCurve` I'm not aware of.

**Comment by pllim** [comment]
Okay, so if the desired API is to modify `__mul__` to recognize a native `dust-extinction` object, I can do that. I just want to make sure we are all on the same page. Currently, `__mul__` has strict checks. Thanks!

**Comment by karllark** [comment]
Ok.  Now beyond my knowledge (`__mul__`?).  I leave this to others to comment.  :-)

**Comment by pllim** [comment]
No worries. It'll be clear when I get a chance to submit a PR. I think I know what you want now. Thanks! :smile:

**Comment by karllark** [comment]
Ok.  Will look to increase my knowledge once the PR is ready.  ;-)

**Comment by pllim** [comment]
Oh wait... `ext.extinguish(wav, Av=Av)` returns a plain Numpy array. Is there a way to get it back as a model natively in `dust_extinction`? I guess that's why the tutorial had to wrap the result around `ExtinctionCurve(ExtinctionModel1D, ...)`. If it is just plain Numpy array, overwriting `__mul__` might not be possible. :thinking:

**Comment by karllark** [comment]
Yes, just a numpy array.  The idea here is the model is being evaluated for a specific A(V).  Not really correct to return another model I think.  Guess wrapping will be necessary.

**Comment by pllim** [comment]
@karllark , if `extinguish` does not return a model, how do you use it in your science? Don't you need to interpolate it to apply it to some existing spectrum?

**Comment by karllark** [comment]
The interpolation is done as part of the extinguish function.   The wavelength grid to be used for interpolation is passed as a parameter.

**Comment by pllim** [comment]
There is now a bridge to `dust-extinction` in #251. I'll mark this as resolved as I have not heard any demand for interface into any other packages listed above.
