### ISSUE TITLE
ftp.stsci.edu no longer working?

### ISSUE THREAD

**Issue by krislars** [spacetelescope/synphot_refactor#147]
May be just a temporary outage, but the code does rely heavily on files such as 
 ftp://ftp.stsci.edu/cdbs/calspec/alpha_lyr_stis_008.fits

Is there an alternate address?

I am working on a tutorial that uses synphot in google colaboratory, where ftp access is seamless and uploading data files is far from easy.

**Comment by pllim** [comment]
You can use HTTP access as documented in https://github.com/spacetelescope/pysynphot/issues/46#issuecomment-329792670 .

**Comment by pllim** [comment]
If you are using a Mac, FTP probably won't work for you anymore.

**Comment by krislars** [comment]
Can I get the filter curves there, too?  I don't know how to get a jupyter notebook to unzip a tar file on the fly.

**Comment by krislars** [comment]
Ah, figured it out!
http://ssb.stsci.edu/cdbs/comp/nonhst/johnson_v_004_syn.fits

Thanks!

**Comment by pllim** [comment]
Glad you found a way!
