### ISSUE TITLE
Effective area filter info doc update

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/synphot_refactor#163]
Need to include an example of how to deal with filter curves that are provided in effective area rather than unitless throughput. In such cases, the effective area can be treated the same as throughput with the area set to be unity in the units of the effective area. For example, XMM OM throughput curves are in (EFF_AREA * 100) m^2, for which we would divide each value by 100 and then set the primary mirror area to be 1 m^2.

(this closes #162)

**Comment by pllim** [comment]
@tddesjardins , do you have a snippet you want to include? Where in the documentation would you like to see this?

p.s. A pull request is even better!
