### ISSUE TITLE
Start of manual should address non-expert

### ISSUE THREAD

**Issue by joeharr4** [spacetelescope/synphot_refactor#165]
I'm new to synphot.  The start of the manual here:

https://synphot.readthedocs.io/en/latest/

should quickly let astronomers unfamiliar with synphot and even astropy know what the package is for.  It should give some examples, including plots, etc., of what it's for, so we can decide whether it's worth spending an hour digging in to learn if it's what we need.  Graphics would be a very good idea.  A specific question I have that is not answered: Can synphot be used for wavelength calibration (it appeared in a google search for that)?  Or, is there a package that uses it for that purpose?

Suggestions:
1. Start with the "synphot simulates" paragraph and the following list.  Follow with the two lines above that paragraph, which name the two packages.  Say, "see below for examples".
2. Move the opening historical notes down to a History section.  This does not need to be near the top.
3. Move modeling paragraph before the first example to after the examples.  ONLY if you are deluged with people asking about this and must put something even above the first newbie example to staunch the flow of email, replace with a line saying, "(AstroPy experts: See modeling note, below.)"  You can make that an internal link.
4. Fix the example so it runs.  It seems to be missing the line 
`from astropy import units as u`
from the top of the first example block.  Even then, the plotting command does not actually do anything (on my updated astroconda, running on Ubuntu 18.04).  No plot appears and no file is saved.
5. Start with several much-simpler examples, things that can be done in 2-3 lines and that do not require many imports or such lengthy comments.
6. Include every graphic made by the examples, so people don't need to fire up Python to see them, or in case the examples don't run on their setup, or they haven't yet installed astroconda or synphot and are just shopping at this point.

Consider a name change to emphasize that this is spectroscopy package.  synspecphot, for example.

Thanks,

--jh--

**Comment by pllim** [comment]
Hello. Thank you for your interest and comments. I'll keep them in mind next time I update the documentation.

> No plot appears and no file is saved.

Try setting your Matplotlib to interactive mode.

> Consider a name change

While I appreciate the suggestion, changing a released package's name is not trivial and I'll rather not do that at this time.

**Comment by joeharr4** [comment]
Thanks.

There is no access to matplotlib in the demo.  You must import it internally.  But, yes, when I import it and do plt.show(), I do see the expected plot.  I'd suggest putting that at the top of the demo.

--jh--

**Comment by pllim** [comment]
> Can synphot be used for wavelength calibration

Spectral wavelength calibration belongs more in https://github.com/astropy/specutils or https://github.com/astropy/specreduce . AFAIK, neither uses `synphot`.

**Comment by pllim** [comment]
I moved the history in #177 but feel like the rest would be handled naturally as part of #150. If you feel otherwise, please open pull request(s) with suggested edits. Thank you!
