### ISSUE TITLE
intersphinx link

### ISSUE THREAD

**Issue by astronomyk** [spacetelescope/synphot_refactor#169]
Hi!

Sorry for creating an issue for this, but I didn't know where else to ask it:
Is it possible to do an intersphinx mapping to synphot? If so, what would the link be?

Thanks!

**Comment by pllim** [comment]
No problem. Adding this to your mapping should work. If it does, please close the issue.
```python
{'synphot': ('http://synphot.readthedocs.org/en/latest/', None)}
```

**Comment by astronomyk** [comment]
Hi pllim,

Just a heads up. I tried out your suggestion, but alas to no avail. Here's what I added to my one of my .rst files. I also added an astropy class as a control. The `astropy.Table` links up via intersphinx, however the synphot classes remain without a hyperlink

From my `.rst` file

    :class:`synphot.SourceSpectrum`
    :class:`synphot.models.SourceSpectrum`
    :class:`synphot.models.Empirical1D`
    :class:`astropy.table.Table`

In my sphinx `conf.py` file I have the following:

    intersphinx_mapping = {'python' : ('https://docs.python.org/',  None),
                           'astropy': ('http://docs.astropy.org/en/latest/', None),
                           'synphot': ('http://synphot.readthedocs.org/en/latest/', None)
                           }

I guess sphinx is looking for a `objects.inv` on the synphot readthedocs site, but not finding one. I have no idea if this is generated automatically by readthedocs, or whether the package owner needs to do that. I'd probably get the answer if I googled a bit.

Anyway I'll close the issue now, as I have my answer for the time being.  I'll look into it and reply if I get a solution for my own package.

Thanks again!
Kieran

**Comment by astronomyk** [comment]
Hi again,

so a bit of googling later, it seems that readthedocs does indeed provide the `objects.inv` file, and sphinx was downloading it. (fyi, it's move to here http**s**://synphot.readthedocs.**io**/en/latest/) But the class that I'd chosen as my example (`SourceSpectrum`) doesn't work. I.e. no link is generated for it. Once I added `Empirical1D` it linked up fine. Weird.

Anyway thanks and sorry for the spam.
Kieran
