### ISSUE TITLE
Update conda install line with conda channel info

### ISSUE THREAD

**Issue by eblur** [spacetelescope/synphot_refactor#176]
[The conda install line listed on the front page doesn't work](https://synphot.readthedocs.io/en/latest/).

I recommend changing the conda install line to:
`conda install -c http://ssb.stsci.edu/astroconda synphot`

**Comment by pllim** [comment]
Ah, okay. The sentence right before the install command was "from Astroconda", which implies user has added Astroconda URL to their channel config. But I see that it is too vague. Will change when I get a chance. Or PR is welcome too. Thanks for pointing this out!

**Comment by eblur** [comment]
Yes, I know. After clicking that link, it takes two clicks (and scrolling) to get to the directions on installing astroconda. It's a subtle change that people less experienced with conda and the whole channel infrastructure will appreciate!
