### ISSUE TITLE
personal message

### ISSUE THREAD

**Issue by astronomyk** [spacetelescope/synphot_refactor#216]
Hi @pllim 

I'd like to ask you a couple of questions regarding the future of synphot via email if possible. My email address is kdleschinski@gmail.com. If you'd prefer I can send you a LinkedIn message, but I'm not a huge fan of that platform.

Cheers,
Kieran

**Comment by pllim** [comment]
Hi Kieran,

It would be best if we could discuss it via STScI Help Desk platform. Please go to https://stsci.service-now.com/hst . If you mentioned my name specifically in your request, I will definitely get it.

Thank you for reaching out to us,
Pey-Lian
