### ISSUE TITLE
Retrieve the files from CRDS 

### ISSUE THREAD

**Issue by msrdinesh** [spacetelescope/synphot_refactor#227]
Hii, I am new to synphot, I was trying to follow [this](https://spacetelescope.github.io/training-library/synphot.html#Construct-and-Plot-a-Spectrum) tutorial I got the error while following the code:
```
from matplotlib import pyplot as plt
from astropy import units as u

import numpy as np
import synphot as syn
import stsynphot as stsyn
import os
syn.conf.vega_file
stsyn.Vega.plot(right=20000, left=1000, flux_unit=syn.units.FLAM, title='Vega Spectrum')
```

ErrorMessage :

> AttributeError                            Traceback (most recent call last)
<ipython-input-39-474900c97719> in <module>
----> 1 stsyn.Vega.plot(right=20000, left=1000, flux_unit=syn.units.FLAM, title='Vega Spectrum')

> AttributeError: 'NoneType' object has no attribute 'plot'

I couldn't follow the instruction of [configuration](https://spacetelescope.github.io/training-library/synphot.html#Configuration) block (retrieving files from CRDS). Also, at a few places, it was written "pysynphot" instead of "synphot". 

Please explain the steps for retrieving the CRDS files or any resources to do so.
Thanks in advance!

**Comment by pllim** [comment]
Hi. If your goal is to patch #206 as you indicated yesterday, you do not need `stsynphot`. But if you want to run the tutorial anyway, you need to refer to https://stsynphot.readthedocs.io/en/latest/ for instructions to get the data. Hope this helps.

**Comment by msrdinesh** [comment]
Hii, to run the following code snipped mentioned in the issue,
`sirius_spec = syn.SourceSpectrum.from_file(os.path.join(os.environ['PYSYN_CDBS'], 'calspec', 'sirius_stis_001.fits'))` 
I think, we need the data. So, I was trying the understand how to retrieve data for synphot.

**Comment by pllim** [comment]
What do you need the data for exactly? Can you please clarify?

**Comment by msrdinesh** [comment]
In the issue [206](https://github.com/spacetelescope/synphot_refactor/issues/206). In the code, please see 5th line in the code. 
`sirius_spec = syn.SourceSpectrum.from_file(os.path.join(os.environ['PYSYN_CDBS'], 'calspec', 'sirius_stis_001.fits'))` 
when I run this line, I got the following error

> WARNING: Failed to load Vega spectrum from /grp/hst/cdbs//calspec/alpha_lyr_stis_009.fits; 

> Functionality involving Vega will be cripped: [Errno 2] No such file or directory: '/grp/hst/cdbs//calspec/alpha_lyr_stis_009.fits' [stsynphot.spectrum]
> Traceback (most recent call last):
>   File "test.py", line 7, in <module>
>     sirius_spec = syn.SourceSpectrum.from_file(os.path.join(os.environ['PYSYN_CDBS'], 'calspec', 'sirius_stis_001.fits')) 
>   File "/home/msrdinesh/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'PYSYN_CDBS'

Please help me on how to handle this. I thought it can be solved if we retrieve data from CRDS.

**Comment by pllim** [comment]
Instructions on how to set up the data should be in https://stsynphot.readthedocs.io/en/latest/#installation-and-setup

**Comment by msrdinesh** [comment]
Ok, thanks @pllim for your patience, I will read and work on it.

**Comment by msrdinesh** [comment]
I have downloaded the files from [this](https://archive.stsci.edu/) website and placed them manually. It worked.
