### ISSUE TITLE
MNT: Update default Vega?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#258]
I see that `010` is now available at https://archive.stsci.edu/hlsps/reference-atlases/cdbs/current_calspec/ . The one here is still `009`.

https://github.com/spacetelescope/synphot_refactor/blob/7733b2be7dbdaab58b8fac9ba3d8453e310cff75/synphot/config.py#L25

Should we update it, @vglaidler , @sean-lockwood , or @tddesjardins ?

**Comment by sean-lockwood** [comment]
The HST ETC 28.2 is using v008 for internal consistency reasons.

@vglaidler We may want to keep track of this to keep the ETC normalization in sync with the input spectrum as we upgrade Synphot packages/versions.

**Comment by pllim** [comment]
So, looks like `synphot` is already out of sync with HST ETC. Should I just update it then? Please advise. Thanks!
