### ISSUE TITLE
Documentation request for Vegamag normalization

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/synphot_refactor#262]
The current version of the documentation on the [normalization function](https://synphot.readthedocs.io/en/latest/api/synphot.spectrum.BaseSourceSpectrum.html#synphot.spectrum.BaseSourceSpectrum.normalize) does not make it clear that a Vega SourceSpectrum object must be supplied with the `vegamag=` keyword to normalize by vegamags. 

The existence of the SourceSpectrum.from_vega() method (and docstrings in synphot.units.convert_flux) implied to me that the keyword was optional and the system would run SourceSpectrum.from_vega() if a vega spectrum was not supplied (and maybe it should? It would greatly simplify users' code)

**Comment by pllim** [comment]
> maybe it should?

I had decided against it when it was written because explicit is better than implicit. It is better that it fails than to make assumption that might be wrong. User might forget to set to their favorite Vega spectrum and gets the wrong value if `from_vega()` is used silently in the background.
