### ISSUE TITLE
Possible bug in rebinning or unit conversion

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/synphot_refactor#272]
Example code that produces this bug is in this gist: https://gist.github.com/ariedel/3467fb6ebfe443b256b138432240561f

(requires numpy, matplotlib, pysynphot, and synphot)
run with:
```
python synphotexample.py synphot
```
or
```
python synphotexample.py pysynphot
```

This code creates a flat spectrum (in fnu) and attempts to trim/rebin it within a small wavelength range.

If you select pysynphot you get a correctly rebinned flat spectrum (though note: pysynphot doesn't get the units of the wavelength or flux passed in, so it assumes they're Angstroms and PHOTLAM even though they were created as microns and mJy)

If you select synphot, the output spectrum is no longer flat - it has jagged features.

If you remove the lines of code (47,48,49) that apply units to the spectra (therefore not passing in units of wavelength or flux so that it assumes they're Angstroms and PHOTLAM), synphot will work just like pysynphot does. 

My inference is that there's a problem with either synphot's Observation creation or unit conversions, because the actual rebinning code is the same in both modules.

**Comment by pllim** [comment]
I don't think it is a bug. If anything, PySynphot wasn't being used properly. You can see my comments on your Gist at https://gist.github.com/pllim/35198b0e486493c1de015302983ce093 (look for `pllim`).

Once the unit handling is fixed for PySynphot, they agree:

![syn_pysyn_adric](https://user-images.githubusercontent.com/2090236/84526603-a7a1b800-acab-11ea-961b-bad7319f04ee.jpg)

So, if you are used to making PySynphot think that values passed in are not in the units they are really in, basically, you need to do the same with `synphot`, as you reported above. If you discard units before passing them into `synphot`, it falls back to PySynphot behavior, as you have observed.

I am not sure if there is anything to fix here.

**Comment by pllim** [comment]
@ariedel , can we close this or is there something I need to do here? Please advise. Thanks!

**Comment by pllim** [comment]
I am closing this for now. If you think it is still an issue, feel free to re-open. Thanks!
