### ISSUE TITLE
Convolving spectrum with LSF

### ISSUE THREAD

**Issue by chazshapiro** [spacetelescope/synphot_refactor#328]
Hello... is there a built-in way (synphot or astropy) to convolve a spectrum with a line spread function?  I have done it by evaluating the spectrum at very small intervals, using scipy.signal.convolve on that array with my LSF, and then defining a new empirical spectrum using the result.  I wonder if I'm overlooking an easier way.  Thanks, CS.

**Comment by pllim** [comment]
Hello and thank you for your interest in `synphot`!

Unfortunately, LSF is not supported by this package. However, your use case might be supported by [specutils](https://specutils.readthedocs.io/en/stable/). 

Perhaps have a look at [convolution_smooth](https://specutils.readthedocs.io/en/stable/api/specutils.manipulation.convolution_smooth.html) or [gaussian_smooth](https://specutils.readthedocs.io/en/stable/api/specutils.manipulation.gaussian_smooth.html).
