### ISSUE TITLE
Error message verbosity toggle

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/synphot_refactor#339]
### Description

The errors produced by Synphot are significantly more detailed than those produced by its predecessor, Pysynphot. This has the unexpected side effect of causing the Pandeia ETC to occasionally emit lengthy errors that are not useful to users. In roughly 20 cases, the messages are so long that they overflowed the database field meant to store results or error messages, and the contents are no longer valid JSON. (The affected calculations all had errors, so no actual results have been lost)

I would like to see a toggle or system-level environment variable that would control the level of detail in the output. 
For instance, for the Empirical1D model, _process_neg_flux produces an occasionally lengthy warning that would still have useful information if cut down to just the first line.

**Comment by pllim** [comment]
I would first like to understand the problem here. In the specific `_process_neg_flux` case.

https://github.com/spacetelescope/synphot_refactor/blob/cb3ff4b05ae5f20419b5b4a781eac9496f24936c/synphot/models.py#L395

1. You can avoid the warning completely if you do `keep_neg=True`.
2. You can filter out the warning as you like using https://docs.python.org/3/library/warnings.html .

Why is it giving you error with long traceback?

I feel like adding a toggle to make ETC happy should be done downstream in ETC, not in this package.

**Comment by ariedel** [comment]
I'm looking at this in more detail.
1. all of the errors that caused long messages were SynphotError (at least one was a more specific synphot.exceptions.PartialOverlap) raised by the synphot.spectrum.SourceSpectrum.normalize() command as run on our "photsys" type normalization bands, which implies it's one of our selected johnson/cousins/sdss/2mass bandpass filters being used in every case (and therefore possibly causing it). All of them printed out the full arrays involved
2. The last db-breaking lengthy message comes from Pandeia Engine 1.6.1, which puts it somewhere between June 2021 and February 2022. That either means it's already been fixed, by us or by a change in a more recent version of Synphot; or we simply haven't had enough traffic to get another user triggering it.

I have a few JSON fragments, but I worry about the possibly proprietary nature of the array information in the error message and I'd prefer to send them privately.

And yes, I'm looking into doing the trimming within the ETC's custom exceptions.

**Comment by pllim** [comment]
While I understand why ETC wants to hide stuff, `synphot` should be verbose enough so a typical user gets enough information to debug if something is wrong. So I will close this as "won't fix" here but will be happy to consult on your patch on the ETC side. Good luck!
