### ISSUE TITLE
Publish M1 wheels

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#351]
### Description

@larrybradley said that `synphot` should publish M1-compatible wheels in its next release in a similar fashion as `photutils`.

https://github.com/astropy/photutils/blob/1ba4195d32cc44fa19b76eff80fb30da5f872815/.github/workflows/publish.yml#L56

**Comment by larrybradley** [comment]
I use the OpenAstronomy publish workflow in `photutils`.

**Comment by pllim** [comment]
I guess I should too. I just need a quiet day to actually do it...
