### ISSUE TITLE
read_fits_spec does not accept kwargs

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/synphot_refactor#355]
### Description

specio.read_fits_spec does not take `**kwargs` even though specio.read_spec passes them in.

### Expected behavior

I expected to be able to pass a keyword argument for astropy.io.ascii.read() to synphot.spectrum.SourceSpectrum.from_file(), and it worked until I got to a .fits file.

### Actual behavior

The keyword arguments worked until my code got to the first fits file, read_fits_spec crashed because it didn't recognize the additional keyword it was being fed.

### Steps to Reproduce

```
import synphot as syn
sp = syn.spectrum.SourceSpectrum.from_file(filepath, guess=False)
```
If filepath is an ascii file, the code will succeed. If filepath is a .fits file, it will fail with `TypeError: read_fits_spec() got an unexpected keyword argument 'guess'`

(I know astropy.io.fits.read() doesn't have a "guess" option, but manual testing shows that it's ignored.)

### System Details

macOS-10.16-x86_64-i386-64bit
Python 3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ]
Numpy 1.23.4
astropy 5.2
Scipy 1.9.3
Matplotlib 3.6.2
Synphot 1.1.1

**Comment by pllim** [comment]
I don't understand this request. Why are you trying to pass an invalid keyword for the given file format?

**Comment by ariedel** [comment]
I was trying to pass a valid keyword for text files, to the read_spec() method, in a set-and-forget type way.

**Comment by pllim** [comment]
I think should check the file type downstream and set the kwargs as appropriate. Otherwise, you run the risk of passing in things you think you are not but actually it is used in a way you don't want it to be used.

**Comment by ariedel** [comment]
Fair. I've already worked around it in that fashion.

**Comment by ariedel** [comment]
I'll close this.
