### ISSUE TITLE
Conda-forge release for M1 mac

### ISSUE THREAD

**Issue by drewoldag** [spacetelescope/synphot_refactor#358]
### Description
Currently synphot is available as a source distribution on PyPI, and can be built locally on an M1 mac when a user `pip install`s. However, there isn't a distribution to support the M1 mac available on conda-forge. A `noarch` distribution would be sufficient. At this point though, packages that take a dependency on `synphot` can't be `conda install`ed on M1 macs.

### Additional context
Running the following on an M1 mac results in the following: 
```
% micromamba install -c conda-forge synphot
pkgs/main/noarch                                              No change
pkgs/r/osx-arm64                                              No change
pkgs/main/osx-arm64                                           No change
pkgs/r/noarch                                                 No change
conda-forge/osx-arm64                                         No change
conda-forge/noarch                                  11.8MB @  14.3MB/s  0.8s

Pinned packages:
  - python 3.10.*

error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ synphot does not exist (perhaps a typo or a missing channel).
```

**Comment by pllim** [comment]
Not sure if we can do noarch because it has C-extension.

Would need a PR here to add it: https://github.com/conda-forge/synphot-feedstock/

**Comment by pllim** [comment]
Not sure when I can get to this but theoretically instructions are at https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by pllim** [comment]
Did you resolve this on your end? I get conflicting reports from your users, so now I am not sure if there is actually anything needing fixing here.

**Comment by drewoldag** [comment]
This has not been resolved on our end at this point. If creating a M1 distribution is possible that would still be ideal.

**Comment by pllim** [comment]
But your colleague reported successful installation at https://github.com/dirac-institute/sorcha/issues/396#issuecomment-1648350763 . I don't understand.

**Comment by pllim** [comment]
Maybe https://github.com/conda-forge/synphot-feedstock/pull/21 will do it but I cannot be sure until you actually try this downstream... 🤷

**Comment by drewoldag** [comment]
The successful install was on a M2 mac, we were seeing the failures on M1s. It _seems_ as though only the M1 mac installs are problematic. We haven't tried a windows install, but linux and M2 seem to work as expected.

**Comment by pllim** [comment]
@drewoldag , thanks for your patience. I just merged https://github.com/conda-forge/synphot-feedstock/pull/21 . Please try again next week and let me know.

**Comment by pllim** [comment]
Given https://github.com/dirac-institute/sorcha/issues/396#issuecomment-1673630692 , closing this as solved.

**Comment by drewoldag** [comment]
Thanks a bunch for your help with with @pllim!
