### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#393]
When Python 3.13 is out, need to:

1. Add CI for py313 -- Done in https://github.com/spacetelescope/synphot_refactor/pull/394
2. Add wheel build for py313 -- Done in https://github.com/spacetelescope/synphot_refactor/pull/394
3. New release so the wheels get pushed out and for conda-forge to pick up (nightly already available)
4. Update CI to use py313 regularly

Was reminded by https://github.com/spacetelescope/synphot_refactor/pull/392

**Comment by lpsinger** [comment]
You don't necessarily need to wait until Python 3.13 is released. There is a [prerelease mode for actions/setup-python](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases) that ought to allow you to test against Python 3.13. Many packages (numpy, scipy) have already released wheels for Python 3.13.

**Comment by pllim** [comment]
True, but no one really asked for it here yet, so... 😬

**Comment by pllim** [comment]
Testing is done in https://github.com/spacetelescope/synphot_refactor/pull/394 . Would be nice if I have a way to upload nightly wheel for synphot instead of doing a PyPI release before Python 3.13 stable is out. We will see...

Thanks for the ping!

**Comment by pllim** [comment]
BTW, I unleashed the nightly wheel at https://anaconda.org/STScI/synphot
