### ISSUE TITLE
SpectralElement AttributeError: 'Table' object has no attribute 'lower'

### ISSUE THREAD

**Issue by gavinramsay** [spacetelescope/synphot_refactor#402]
Hi
I've got a file which contains a passband. Im trying to read it in as a SpectralElement but get this error:

gHiper = SpectralElement.from_file(data)

where data contains two cols, wave and flux_col

AttributeError: 'Table' object has no attribute 'lower'

any idea what 'lower' means? 

many thanks
Gavin

**Comment by pllim** [comment]
Hello and thanks for reaching out.

Is `data` a file name or a `Table` object? Can you please post the full traceback?

**Comment by gavinramsay** [comment]
thanks for responding! 

I dont understand much of the deeper python language terms but this is where i insert the data file:

data = Table.read('/Users/**/soft/stsci_python-2.12/pysynphot/data/generic/GTC_HIPERCAM.g_s_3.dat', format='ascii', names=('row','wave','flux_col'))

so possibly an object. but could be wrong!

many thanks for taking the trouble to reply.

**Comment by pllim** [comment]
Does this work for you?

```python
gHiper = SpectralElement.from_file("/your/path/to/GTC_HIPERCAM.g_s_3.dat")
```

**Comment by pllim** [comment]
If you must build from `Table` columns, it would look more like this:

https://synphot.readthedocs.io/en/latest/synphot/bandpass.html#arrays

**Comment by gavinramsay** [comment]
thats great. i was going round in circles but the above works. thanks!
