### ISSUE TITLE
Add support for L-band bandpass

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#60]
Mainly for JWST support.

From **Vicki Laidler** (March 10, 2014):

> Photometric support for infrared bands is TBD. There will
> certainly be some, but which bands has not yet been decided.
> We can certainly track that this has been requested. I'd
> want to know which photometric system the L filter that is desired.

From **Timothy Pickering** (March 10, 2014):

> On JWST, there is F356W on NIRCAM that is analogous to L,
> but not quite the same. There are different systems that define L
> differently. Some people say L when they mean L', etc. The
> bandpass also changes with precipitable water. Ground-based
> mid-IR photometry is pretty icky business.

Any support for this probably involves adding a file into CRDS.

**Comment by pllim** [comment]
It's been 6 years. I have asked ETC again to see if there is still a need.

**Comment by vglaidler** [comment]
I think you can close this, at least from our perspective. I haven't heard any discussion of L band filters in a few years. If it comes up again, we can file a new ticket.

cc @bholler
