### ISSUE TITLE
Continuum normalized spectrum

### ISSUE THREAD

**Issue by pllim** [spacetelescope/synphot_refactor#75]
A continuum normalized spectrum is created by dividing a real source spectrum with a model of the background. It has flux ratio instead of flux, where absorption lines have values `<1` and emission `>1`. `pysynphot` in ASTROLIB does not support this. Is it overkill to support it in the `astropy` implementation, or can we just simply ask people to use `astropy.modeling` directly for this?

**Comment by purmortal** [comment]
Hi, do you have any solution?

**Comment by pllim** [comment]
Try ask at https://github.com/astropy/specutils
